import React, { useState } from 'react';
import { UploadCloud, FileText, Image as ImageIcon, Sparkles, CheckCircle2, Loader2, ArrowRight } from 'lucide-react';
import BeeAnimatedMascot from './BeeAnimatedMascot';
import { generateFlashcardsFromText } from '../services/geminiService';
import { db } from '../services/storageService';

export default function FileScanner({ onDeckCreated }) {
  const [inputText, setInputText] = useState('');
  const [deckTitle, setDeckTitle] = useState('');
  const [isScanning, setIsScanning] = useState(false);
  const [scanStep, setScanStep] = useState(0);
  const [generatedCards, setGeneratedCards] = useState([]);
  const [extractedFileMeta, setExtractedFileMeta] = useState(null);

  const handleFileUpload = (e) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setExtractedFileMeta({
      name: file.name,
      size: (file.size / 1024).toFixed(1) + ' KB',
      type: file.type
    });
    setDeckTitle(file.name.replace(/\.[^/.]+$/, ''));

    // Read text content
    const reader = new FileReader();
    reader.onload = (evt) => {
      const text = evt.target?.result || '';
      setInputText(text);
    };
    reader.readAsText(file);
  };

  const handleStartAiScan = async () => {
    if (!inputText.trim() && !extractedFileMeta) return;
    setIsScanning(true);
    setScanStep(1);

    try {
      setTimeout(() => setScanStep(2), 700);
      const cards = await generateFlashcardsFromText(inputText || 'Cell Biology and Energy Synthesis', 5);
      setTimeout(() => {
        setGeneratedCards(cards);
        setIsScanning(false);
      }, 1400);
    } catch (err) {
      console.error(err);
      setIsScanning(false);
    }
  };

  const handleSaveDeck = async () => {
    if (!generatedCards.length) return;

    const newDeckId = 'deck-' + Date.now();
    const nowIso = new Date().toISOString();

    const newDeck = {
      id: newDeckId,
      title: deckTitle || 'New AI Generated Deck',
      description: `Generated by Bee AI from ${extractedFileMeta?.name || 'study notes'}.`,
      subjectCategory: 'General Study',
      tags: ['ai-generated', 'gemini'],
      createdAt: nowIso,
      updatedAt: nowIso
    };

    await db.decks.add(newDeck);

    const cardsToInsert = generatedCards.map((c, idx) => ({
      id: `card-${newDeckId}-${idx}`,
      deckId: newDeckId,
      cardType: c.cardType || 'flashcard',
      frontContent: c.frontContent,
      backContent: c.backContent,
      options: c.options,
      hintText: c.hintText,
      dynamicMnemonic: c.dynamicMnemonic,
      easeFactor: 2.5,
      intervalDays: 0,
      repetitions: 0,
      dueDate: new Date().toISOString().split('T')[0],
      status: 'new'
    }));

    await db.cards.bulkAdd(cardsToInsert);

    if (onDeckCreated) {
      onDeckCreated(newDeckId);
    }
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* Header Banner */}
      <div className="glass-panel p-6 border-sky-500/30 flex items-center justify-between">
        <div>
          <div className="flex items-center gap-2">
            <Sparkles className="text-sky-400" size={24} />
            <h2 className="text-2xl font-bold text-white font-display">AI Scan & Deck Studio</h2>
          </div>
          <p className="text-sm text-slate-400 mt-1">
            Upload PDFs, handwritten notes, textbook scans, or paste text to auto-generate active recall cards!
          </p>
        </div>
        <BeeAnimatedMascot size="lg" animated={true} speechBubble="Bee is ready to scan!" />
      </div>

      {/* Multimodal Dropzone & Text Area */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Dropzone */}
        <div className="glass-panel p-6 border-dashed border-2 border-slate-700 hover:border-sky-500 transition-all flex flex-col items-center justify-center text-center relative overflow-hidden group">
          {/* Holographic Scanner Beam when scanning */}
          {isScanning && (
            <div className="absolute inset-x-0 h-1 bg-gradient-to-r from-transparent via-sky-400 to-transparent shadow-[0_0_20px_#1ea5fc] animate-laser-scan z-20" />
          )}

          <input
            type="file"
            accept=".pdf,.txt,.md,.png,.jpg,.jpeg"
            onChange={handleFileUpload}
            className="absolute inset-0 opacity-0 cursor-pointer z-10"
          />

          <div className="p-4 rounded-2xl bg-sky-500/10 text-sky-400 mb-3 group-hover:scale-110 transition-transform">
            <UploadCloud size={36} />
          </div>

          <h3 className="text-base font-bold text-white mb-1">
            {extractedFileMeta ? extractedFileMeta.name : 'Drag & Drop PDF or Image Scans'}
          </h3>
          <p className="text-xs text-slate-400 mb-3">
            Supports PDF, JPG/PNG Scans, Handwritten Notes, or Text Files
          </p>
          <span className="text-[11px] font-semibold text-sky-400 bg-sky-500/10 border border-sky-500/20 px-3 py-1 rounded-full">
            Browse File
          </span>
        </div>

        {/* Pasteable Text Area */}
        <div className="glass-panel p-6 flex flex-col justify-between space-y-4">
          <div>
            <label className="block text-xs font-bold text-slate-300 uppercase tracking-wider mb-2">
              Or Paste Lecture Notes / Text
            </label>
            <textarea
              value={inputText}
              onChange={(e) => setInputText(e.target.value)}
              placeholder="Paste lecture text, key definitions, or exam topics here..."
              className="w-full h-36 bg-slate-900/90 border border-slate-800 focus:border-sky-500 rounded-xl p-3.5 text-sm text-slate-200 placeholder-slate-500 outline-none resize-none"
            />
          </div>

          <div className="flex items-center justify-between">
            <input
              type="text"
              value={deckTitle}
              onChange={(e) => setDeckTitle(e.target.value)}
              placeholder="Deck Title (e.g. Biology Ch 3)"
              className="bg-slate-900 border border-slate-800 rounded-xl px-3 py-2 text-xs text-slate-200 outline-none w-1/2"
            />

            <button
              onClick={handleStartAiScan}
              disabled={isScanning || (!inputText.trim() && !extractedFileMeta)}
              className="btn-primary text-xs disabled:opacity-50"
            >
              {isScanning ? (
                <>
                  <Loader2 className="animate-spin" size={16} />
                  Scanning...
                </>
              ) : (
                <>
                  <Sparkles size={16} />
                  Generate Cards
                </>
              )}
            </button>
          </div>
        </div>
      </div>

      {/* Generated Cards Preview Section */}
      {generatedCards.length > 0 && (
        <div className="glass-panel p-6 space-y-4 border-sky-500/30">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-lg font-bold text-white">Generated Active Recall Cards ({generatedCards.length})</h3>
              <p className="text-xs text-slate-400">Review your generated cards before saving to your library</p>
            </div>

            <button onClick={handleSaveDeck} className="btn-primary text-xs">
              <CheckCircle2 size={16} />
              Save to My Decks
            </button>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2">
            {generatedCards.map((card, idx) => (
              <div key={idx} className="p-4 rounded-xl bg-slate-900/90 border border-slate-800 hover:border-sky-500/40 space-y-2">
                <div className="flex items-center justify-between text-xs text-sky-400 font-bold uppercase">
                  <span>Card #{idx + 1} ({card.cardType})</span>
                  <span className="text-amber-400 text-[10px]">✨ Gemini Synthesized</span>
                </div>
                <p className="text-sm font-semibold text-slate-200">Q: {card.frontContent}</p>
                <p className="text-xs text-slate-400 border-t border-slate-800 pt-2">A: {card.backContent}</p>
                {card.dynamicMnemonic && (
                  <p className="text-[11px] text-amber-300/90 italic bg-amber-500/10 p-2 rounded-lg border border-amber-500/20">
                    💡 Mnemonic: {card.dynamicMnemonic}
                  </p>
                )}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
